server:
  port: 9110

sql-db: tech
sql-username: root
sql-password: mysql
sql-servername: localhost

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${sql-servername}:3306/${sql-db}?autoReconnect=true&useSSL=false
    username: ${sql-username}
    password: ${sql-password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-timeout: 15000
      auto-commit: false
      pool-name: engine_pool_backend
      minimum-idle: 5
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
    locations: classpath:database

